<!-- include(01-intro.md) -->
<!-- include(02-registros.md) -->
<!-- include(03-logins.md) -->
<!-- include(04-convites.md) -->
<!-- include(05-redefinicoes-senha.md) -->
<!-- include(06-perfis.md) -->
<!-- include(07-personificacoes.md) -->
<!-- include(08-conteudos.md) -->
<!-- include(09-navegacao.md) -->
<!-- include(10-objetivos.md) -->
<!-- include(11-niveis-de-ensino.md) -->
<!-- include(12-segmentos-de-ensino.md) -->
<!-- include(13-pacotes.md) -->
<!-- include(14-acessos.md) -->
<!-- include(15-cancelamentos.md) -->
<!-- include(16-videos.md) -->
<!-- include(17-checkout.md) -->
<!-- include(18-pagamentos.md) -->
<!-- include(19-eventos.md) -->
<!-- include(21-reembolso.md) -->
<!-- include(22-descontos.md) -->
<!-- include(23-redacao.md) -->
<!-- include(24-comentarios.md) -->
