form = Quiz::Form.create!(
  id: 2,
  name: 'Gabarito ENEM 2017',
  description: 'Preencha para receber quantas perguntas você acertou na prova do enem 2017',
  form_type: 'answer_grid',
  active: true
)

question_id = 6
45.times do |i|
  question = Quiz::Question.create!(
    id: question_id + i,
    quiz_form_id: form.id,
    statement: "#{i+1}",
    question_type: 'radio'
  )

  {
    "A": "A",
    "B": "B",
    "C": "C",
    "D": "D",
    "E": "E"
  }.each do |description, value|
    Quiz::Alternative.create!(
      quiz_question_id: question.id,
      description: description,
      value: value
    )
  end
end

Quiz::Question.create!(
  id: 52,
  quiz_form_id: form.id,
  statement: 'Qual a matéria da sua prova?',
  question_type:  'text'
)

Quiz::Question.create!(
  id: 53,
  quiz_form_id: form.id,
  statement: 'Qual a cor da sua prova?',
  question_type:  'text'
)

form2 = Quiz::Form.create!(
  id: 3,
  name: 'Informações Gabarito ENEM 2017',
  description: 'Preencha para sabermos mais sobre você',
  form_type: 'standard',
  active: true
)

courses = ['ADMINISTRAÇÃO', 'ADMINISTRAÇÃO DE EMPRESAS', 'ADMINISTRAÇÃO EM SISTEMAS E SERVIÇOS DE SAÚDE', 'ADMINISTRAÇÃO PÚBLICA', 'ADMINISTRAÇÃO PÚBLICA E POLÍTICAS PÚBLICAS', 'ADMINISTRAÇÃO PÚBLICA E SOCIAL', 'AGROECOLOGIA', 'AGROINDÚSTRIA', 'AGRONEGÓCIO', 'AGRONOMIA', 'ALIMENTOS', 'ANÁLISE DE SISTEMAS', 'ANÁLISE DE SISTEMAS DE INFORMAÇÃO', 'ANÁLISE E DESENVOLVIMENTO DE SISTEMAS', 'ANIMAÇÃO', 'ANTROPOLOGIA', 'ANTROPOLOGIA - DIVERSIDADE CULTURAL LATINO-AMERICANA', 'AQUACULTURA', 'AQÜICULTURA', 'ARQUEOLOGIA', 'ARQUEOLOGIA E PRESERVAÇÃO PATRIMONIAL', 'ARQUITETURA E URBANISMO', 'ARQUIVOLOGIA', 'ARTE', 'ARTE E MÍDIA', 'ARTES', 'ARTES CÊNICAS', 'ARTES CÊNICAS COM HABILITAÇÃO EM CENOGRAFIA', 'ARTES CÊNICAS COM HABILITAÇÃO EM INDUMENTÁRIA', 'ARTES PLÁSTICAS', 'ARTES VISUAIS', 'ARTES VISUAIS - ESCULTURA', 'ASTRONOMIA', 'AUTOMAÇÃO INDUSTRIAL', 'BIBLIOTECONOMIA', 'BIBLIOTECONOMIA E CIÊNCIA DA INFORMAÇÃO', 'BIBLIOTECONOMIA E CIÊNCIAS DA INFORMAÇÃO E DA DOCUMENTAÇÃO', 'BIBLIOTECONOMIA E DOCUMENTAÇÃO', 'BIBLIOTECONOMIA E GESTÃO DE UNIDADES DE INFORMAÇÃO', 'BIOCOMBUSTÍVEIS', 'BIOLOGIA', 'BIOMEDICINA', 'BIOQUÍMICA', 'BIOTECNOLOGIA', 'CAFEICULTURA', 'CENOGRAFIA', 'CIÊNCIA AMBIENTAL', 'CIÊNCIA DA COMPUTAÇÃO', 'CIÊNCIA DA INFORMAÇÃO', 'CIÊNCIA E TECNOLOGIA', 'CIÊNCIA E TECNOLOGIA DE ALIMENTOS', 'CIÊNCIA E TECNOLOGIA DE LATICÍNIOS', 'CIÊNCIA ECONÔMICA', 'CIÊNCIA POLÍTICA', 'CIÊNCIA POLÍTICA E SOCIOLOGIA - SOCIEDADE, ESTADO E POLÍTICA NA AMÉRICA LATINA', 'CIÊNCIAS', 'CIÊNCIAS - BIOLOGIA E QUÍMICA', 'CIÊNCIAS - MATEMÁTICA E FÍSICA', 'CIÊNCIAS AGRÁRIAS', 'CIÊNCIAS AGRÁRIAS E DO AMBIENTE', 'CIÊNCIAS AGRÍCOLAS', 'CIÊNCIAS AMBIENTAIS', 'CIÊNCIAS ATMOSFÉRICAS', 'CIÊNCIAS ATUARIAIS', 'CIÊNCIAS BIOLÓGICAS', 'CIÊNCIAS BIOLÓGICAS - BIOTECNOLOGIA E PRODUÇÃO', 'CIÊNCIAS BIOLÓGICAS - ECOLOGIA E BIODIVERSIDADE', 'CIÊNCIAS BIOLÓGICAS - ÊNFASE EM CIÊNCIAS AMBIENTAIS', 'CIÊNCIAS BIOLÓGICAS - GESTÃO AMBIENTAL', 'CIÊNCIAS BIOLÓGICAS - LICENCIATURA OU BACHARELADO', 'CIÊNCIAS BIOLÓGICAS: BIOFÍSICA', 'CIÊNCIAS BIOLÓGICAS: BIOTECNOLOGIA', 'CIÊNCIAS BIOLÓGICAS: MICROBIOLOGIA E IMUNOLOGIA', 'CIÊNCIAS BIOLÓGICAS: MODALIDADE MÉDICA', 'CIÊNCIAS BIOMÉDICAS', 'CIÊNCIAS CONTÁBEIS', 'CIÊNCIAS DA COMPUTAÇÃO', 'CIÊNCIAS DA NATUREZA', 'CIÊNCIAS DA NATUREZA - BIOLOGIA, FÍSICA E QUÍMICA', 'CIÊNCIAS DA NATUREZA - QUÍMICA', 'CIÊNCIAS DA RELIGIÃO', 'CIÊNCIAS DAS RELIGIÕES', 'CIÊNCIAS DE ALIMENTOS', 'CIÊNCIAS DE COMPUTAÇÃO', 'CIÊNCIAS DO CONSUMO', 'CIÊNCIAS DO ESTADO', 'CIÊNCIAS DOS ALIMENTOS', 'CIÊNCIAS E HUMANIDADES', 'CIÊNCIAS ECONÔMICAS', 'CIÊNCIAS ECONÔMICAS - ECONOMIA, INTEGRAÇÃO E DESENVOLVIMENTO', 'CIÊNCIAS EXATAS', 'CIÊNCIAS EXATAS E TECNOLÓGICAS', 'CIÊNCIAS FARMACÊUTICAS', 'CIÊNCIAS FÍSICAS E BIOMOLECULARES', 'CIÊNCIAS HUMANAS', 'CIÊNCIAS HUMANAS - FILOSOFIA', 'CIÊNCIAS HUMANAS - GEOGRAFIA', 'CIÊNCIAS HUMANAS - HISTÓRIA', 'CIÊNCIAS HUMANAS - SOCIOLOGIA', 'CIÊNCIAS IMOBILIÁRIAS', 'CIÊNCIAS JURÍDICAS E SOCIAIS', 'CIÊNCIAS MATEMÁTICAS E DA TERRA', 'CIÊNCIAS NATURAIS', 'CIÊNCIAS NATURAIS - BIOLOGIA', 'CIÊNCIAS NATURAIS - FÍSICA', 'CIÊNCIAS NATURAIS - QUÍMICA', 'CIÊNCIAS NATURAIS E MATEMÁTICA - FÍSICA', 'CIÊNCIAS NATURAIS E MATEMÁTICA - MATEMÁTICA', 'CIÊNCIAS NATURAIS E MATEMÁTICA - QUÍMICA', 'CIÊNCIAS NATURAIS: HABILITAÇÃO EM FÍSICA', 'CIÊNCIAS NATURAIS: HABILITAÇÃO EM QUÍMICA', 'CIÊNCIAS SOCIAIS', 'CIÊNCIAS SOCIAIS - CIÊNCIA POLÍTICA', 'CIÊNCIAS SOCIAIS - LICENCIATURA OU BACHARELADO', 'CIÊNCIAS SOCIAIS - POLÍTICAS PÚBLICAS', 'CIÊNCIAS SOCIOAMBIENTAIS', 'CIÊNCIAS: BIOLOGIA, FÍSICA E QUÍMICA', 'CINEMA', 'CINEMA DE ANIMAÇÃO', 'CINEMA E AUDIOVISUAL', 'COMÉRCIO EXTERIOR', 'COMPUTAÇÃO', 'COMPUTAÇÃO E INFORMÁTICA', 'COMUNICAÇÃO EM MÍDIAS DIGITAIS', 'COMUNICAÇÃO INSTITUCIONAL', 'COMUNICAÇÃO ORGANIZACIONAL', 'COMUNICAÇÃO SOCIAL', 'COMUNICAÇÃO SOCIAL  - RADIALISMO', 'COMUNICAÇÃO SOCIAL - AUDIOVISUAL', 'COMUNICAÇÃO SOCIAL - JORNALISMO', 'COMUNICAÇÃO SOCIAL - PRODUÇÃO EDITORIAL', 'COMUNICAÇÃO SOCIAL - PUBLICIDADE E PROPAGANDA', 'COMUNICAÇÃO SOCIAL - RADIALISMO', 'COMUNICAÇÃO SOCIAL - RADIALISMO/RÁDIO/TV', 'COMUNICAÇÃO SOCIAL - RADIO E TELEVISÃO', 'COMUNICAÇÃO SOCIAL - RELAÇÕES PÚBLICAS', 'COMUNICAÇÃO SOCIAL COM HABILITAÇÃO EM EDITORAÇÃO', 'COMUNICAÇÃO SOCIAL COM HABILITAÇÃO EM PUBLICIDADE E PROPAGANDA', 'COMUNICAÇÃO SOCIAL COM HABILITAÇÃO EM RELAÇÕES PÚBLICAS', 'CONSERVAÇÃO E RESTAURAÇÃO', 'CONSERVAÇÃO E RESTAURAÇÃO DE BENS CULTURAIS MÓVEIS', 'CONSERVAÇÃO E RESTAURO', 'CONSTRUÇÃO DE EDIFÍCIOS', 'CONSTRUÇÃO NAVAL', 'CONTROLADORIA E FINANÇAS', 'CONTROLE DE OBRAS', 'COOPERATIVISMO', 'CURSO SUPERIOR DE TECNOLOGIA EM ENERGIAS RENOVÁVEIS', 'DANÇA', 'DEFESA E GESTÃO ESTRATÉGICA INTERNACIONAL', 'DESENHO INDUSTRIAL', 'DESENVOLVIMENTO RURAL E GESTÃO AGROINDUSTRIAL', 'DESENVOLVIMENTO RURAL E SEGURANÇA ALIMENTAR', 'DESIGN', 'DESIGN - INDUSTRIAL', 'DESIGN - MODA', 'DESIGN DE AMBIENTES', 'DESIGN DE INTERIORES', 'DESIGN DE MODA', 'DESIGN DE PRODUTO', 'DESIGN DIGITAL', 'DESIGN GRÁFICO', 'DESIGN VISUAL', 'DIREÇÃO DE ARTE', 'DIREITO', 'ECOLOGIA', 'ECOLOGIA E ANÁLISE AMBIENTAL', 'ECONOMIA', 'ECONOMIA ECOLÓGICA', 'EDUCAÇÃO ARTÍSTICA - DESENHO', 'EDUCAÇÃO ARTÍSTICA COM HABILITAÇÃO EM ARTES PLÁSTICAS', 'EDUCAÇÃO DO CAMPO', 'EDUCAÇÃO ESPECIAL', 'EDUCAÇÃO FÍSICA', 'EDUCAÇÃO FÍSICA - ÊNFASE EM EDUCAÇÃO FÍSICA E SAÚDE', 'EDUCAÇÃO FÍSICA - LICENCIATURA OU BACHARELADO', 'EDUCAÇÃO FÍSICA - PROMOÇÃO EM SAÚDE E LAZER', 'EDUCAÇÃO FÍSICA - TREINAMENTO ESPORTIVO', 'EDUCAÇÃO FÍSICA E SAÚDE', 'EDUCAÇÃO INFANTIL', 'EDUCOMUNICAÇÃO', 'ELETROMECÂNICA', 'ELETRÔNICA INDUSTRIAL', 'ELETROTÉCNICA INDUSTRIAL', 'ENFERMAGEM', 'ENFERMAGEM - LICENCIATURA OU BACHARELADO', 'ENFERMAGEM E OBSTETRÍCIA', 'ENGENHARIA (CICLO BÁSICO)', 'ENGENHARIA ACÚSTICA', 'ENGENHARIA AEROESPACIAL', 'ENGENHARIA AERONÁUTICA', 'ENGENHARIA AGRÍCOLA', 'ENGENHARIA AGRÍCOLA E AMBIENTAL', 'ENGENHARIA AGROINDUSTRIAL AGROQUÍMICA', 'ENGENHARIA AGROINDUSTRIAL INDÚSTRIAS ALIMENTÍCIAS', 'ENGENHARIA AGRONÔMICA', 'ENGENHARIA AMBIENTAL', 'ENGENHARIA AMBIENTAL E ENERGIAS RENOVÁVEIS', 'ENGENHARIA AMBIENTAL E SANITÁRIA', 'ENGENHARIA AUTOMOTIVA', 'ENGENHARIA BIOMÉDICA', 'ENGENHARIA BIOQUÍMICA', 'ENGENHARIA CARTOGRÁFICA', 'ENGENHARIA CARTOGRÁFICA E DE AGRIMENSURA', 'ENGENHARIA CIVIL', 'ENGENHARIA CIVIL COSTEIRA E PORTUÁRIA', 'ENGENHARIA CIVIL DE INFRAESTRUTURA', 'ENGENHARIA CIVIL EMPRESARIAL', 'ENGENHARIA COMPUTACIONAL', 'ENGENHARIA DA COMPUTAÇÃO', 'ENGENHARIA DA MOBILIDADE', 'ENGENHARIA DE AGRIMENSURA', 'ENGENHARIA DE AGRIMENSURA E CARTOGRÁFICA', 'ENGENHARIA DE AGRONEGÓCIOS', 'ENGENHARIA DE ALIMENTOS', 'ENGENHARIA DE AQUICULTURA', 'ENGENHARIA DE AUTOMAÇÃO', 'ENGENHARIA DE AUTOMAÇÃO INDUSTRIAL', 'ENGENHARIA DE BIOPROCESSOS', 'ENGENHARIA DE BIOPROCESSOS E BIOTECNOLOGIA', 'ENGENHARIA DE BIOSSISTEMAS', 'ENGENHARIA DE BIOTECNOLOGIA', 'ENGENHARIA DE BIOTECNOLOGIA E BIOPROCESSOS', 'ENGENHARIA DE COMPUTAÇÃO', 'ENGENHARIA DE COMPUTAÇÃO E INFORMAÇÃO', 'ENGENHARIA DE CONTROLE E AUTOMAÇÃO', 'ENGENHARIA DE CONTROLE E AUTOMAÇÃO DE PROCESSOS', 'ENGENHARIA DE ENERGIA', 'ENGENHARIA DE ENERGIAS', 'ENGENHARIA DE ENERGIAS RENOVÁVEIS', 'ENGENHARIA DE EXPLORAÇÃO E PRODUÇÃO DE PETRÓLEO', 'ENGENHARIA DE INFRAESTRUTURA', 'ENGENHARIA DE MATERIAIS', 'ENGENHARIA DE MECATRÔNICA', 'ENGENHARIA DE MINAS', 'ENGENHARIA DE MINAS E MEIO AMBIENTE', 'ENGENHARIA DE PESCA', 'ENGENHARIA DE PETRÓLEO', 'ENGENHARIA DE PETRÓLEO E GÁS', 'ENGENHARIA DE PRODUÇÃO', 'ENGENHARIA DE PRODUCAO - HABILITACAO MECANICA', 'ENGENHARIA DE PRODUÇÃO AGROINDUSTRIAL', 'ENGENHARIA DE PRODUÇÃO CIVIL', 'ENGENHARIA DE PRODUÇÃO E SISTEMAS', 'ENGENHARIA DE PRODUÇÃO ELÉTRICA', 'ENGENHARIA DE PRODUÇÃO MECÂNICA', 'ENGENHARIA DE RECURSOS HÍDRICOS E DO MEIO AMBIENTE', 'ENGENHARIA DE REDES DE COMUNICAÇÃO', 'ENGENHARIA DE SAÚDE E SEGURANÇA', 'ENGENHARIA DE SISTEMAS', 'ENGENHARIA DE SOFTWARE', 'ENGENHARIA DE TELECOMUNICAÇÕES', 'ENGENHARIA DE TRANSPORTE E LOGÍSTICA', 'ENGENHARIA DE TRANSPORTES', 'ENGENHARIA DE TRANSPORTES E LOGÍSTICA', 'ENGENHARIA ELÉTRICA', 'ENGENHARIA ELÉTRICA - ELETRÔNICA', 'ENGENHARIA ELÉTRICA - ELETROTÉCNICA', 'ENGENHARIA ELÉTRICA - ENERGIA', 'ENGENHARIA ELÉTRICA - ROBÓTICA E AUTOMAÇÃO INDUSTRIAL', 'ENGENHARIA ELÉTRICA - SISTEMAS DE POTÊNCIA', 'ENGENHARIA ELÉTRICA - SISTEMAS ELETRÔNICOS', 'ENGENHARIA ELÉTRICA - TELECOMUNICAÇÕES', 'ENGENHARIA ELETRÔNICA', 'ENGENHARIA ELETRÔNICA E DE COMPUTAÇÃO', 'ENGENHARIA ELETRÔNICA E DE TELECOMUNICAÇÕES', 'ENGENHARIA FERROVIÁRIA E LOGÍSTICA', 'ENGENHARIA FERROVIÁRIA E METROVIÁRIA', 'ENGENHARIA FÍSICA', 'ENGENHARIA FLORESTAL', 'ENGENHARIA GEOLÓGICA', 'ENGENHARIA HÍDRICA', 'ENGENHARIA INDUSTRIAL', 'ENGENHARIA INDUSTRIAL ELÉTRICA', 'ENGENHARIA INDUSTRIAL MADEIREIRA', 'ENGENHARIA INDUSTRIAL MECÂNICA', 'ENGENHARIA MECÂNICA', 'ENGENHARIA MECÂNICA AERONÁUTICA', 'ENGENHARIA MECÂNICA EMPRESARIAL', 'ENGENHARIA MECÂNICA NAVAL', 'ENGENHARIA MECATRÔNICA', 'ENGENHARIA METALÚRGICA', 'ENGENHARIA NAVAL', 'ENGENHARIA NAVAL E OCEÂNICA', 'ENGENHARIA NUCLEAR', 'ENGENHARIA QUÍMICA', 'ENGENHARIA SANITÁRIA', 'ENGENHARIA SANITARIA E AMBIENTAL', 'ENGENHARIA SANITÁRIA E AMBIENTAL', 'ENGENHARIA TÊXTIL', 'ENOLOGIA', 'ESCULTURA', 'ESTATÍSTICA', 'ESTÉTICA E COSMÉTICA', 'ESTÉTICA E TEORIA DO TEATRO', 'ESTRADAS', 'ESTUDO DE GÊNERO E DIVERSIDADE', 'ESTUDOS DE MÍDIA', 'EVENTOS', 'EXPRESSÃO GRÁFICA', 'FABRICAÇÃO MECÂNICA', 'FARMÁCIA', 'FARMÁCIA E BIOQUÍMICA', 'FILOSOFIA', 'FILOSOFIA - LICENCIATURA OU BACHARELADO', 'FINANÇAS', 'FÍSICA', 'FÍSICA COMPUTACIONAL', 'FÍSICA DE MATERIAIS', 'FÍSICA MÉDICA', 'FISIOTERAPIA', 'FONOAUDIOLOGIA', 'GASTRONOMIA', 'GEMOLOGIA', 'GEOCIÊNCIAS E EDUCAÇÃO AMBIENTAL', 'GEOFISICA', 'GEOGRAFIA', 'GEOGRAFIA - LICENCIATURA OU BACHARELADO', 'GEOLOGIA', 'GEOPROCESSAMENTO', 'GERONTOLOGIA', 'GESTÃO AMBIENTAL', 'GESTÃO COMERCIAL', 'GESTÃO DA INFORMAÇÃO', 'GESTÃO DA PRODUÇÃO INDUSTRIAL', 'GESTÃO DA QUALIDADE', 'GESTÃO DA TECNOLOGIA DA INFORMAÇÃO', 'GESTÃO DE AGRONEGÓCIOS', 'GESTÃO DE COOPERATIVAS', 'GESTÃO DE POLÍTICAS PÚBLICAS', 'GESTÃO DE PRODUÇÃO INDUSTRIAL', 'GESTÃO DE RECURSOS HUMANOS', 'GESTÃO DE SAÚDE', 'GESTÃO DE SERVIÇOS DE SAÚDE', 'GESTÃO DE TURISMO', 'GESTÃO DESPORTIVA E DE LAZER', 'GESTÃO DO AGRONEGÓCIO', 'GESTÃO E ANÁLISE AMBIENTAL', 'GESTÃO E EMPREENDEDORISMO', 'GESTÃO EM LOGÍSTICA', 'GESTÃO EM SAÚDE', 'GESTÃO EM SAÚDE AMBIENTAL', 'GESTÃO EM SAÚDE COLETIVA', 'GESTÃO EM SISTEMAS E SERVIÇOS DE SAÚDE', 'GESTÃO FINANCEIRA', 'GESTÃO HOSPITALAR', 'GESTÃO IMOBILIÁRIA', 'GESTÃO PÚBLICA', 'GESTÃO PÚBLICA PARA O DESENVOLVIMENTO ECONÔMICO E SOCIAL', 'GRAVURA', 'HISTÓRIA', 'HISTÓRIA - AMÉRICA LATINA', 'HISTÓRIA - LICENCIATURA OU BACHARELADO', 'HISTÓRIA - MEMÓRIA E IMAGEM', 'HISTÓRIA DA ARTE', 'HORTICULTURA', 'HOTELARIA', 'HUMANIDADES', 'HUMANIDADES - BI-LI', 'IMAGEM E SOM', 'INFORMÁTICA', 'INFORMÁTICA BIOMÉDICA', 'INFORMÁTICA EM SAÚDE', 'INTERDISCIPLINAR EM ARTES', 'INTERDISCIPLINAR EM ARTES E DESIGN', 'INTERDISCIPLINAR EM ARTES E DESIGN - BI-LI', 'INTERDISCIPLINAR EM BIOSSISTEMAS', 'INTERDISCIPLINAR EM CIÊNCIA E ECONOMIA', 'INTERDISCIPLINAR EM CIÊNCIA E ECONOMIA - BI-LI', 'INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA', 'INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA - BI-LI', 'INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA DO MAR', 'INTERDISCIPLINAR EM CIÊNCIAS', 'INTERDISCIPLINAR EM CIÊNCIAS AGRÁRIAS - BI-LI', 'INTERDISCIPLINAR EM CIÊNCIAS HUMANAS', 'INTERDISCIPLINAR EM CIÊNCIAS HUMANAS - BI-LI', 'INTERDISCIPLINAR EM CIÊNCIAS NATURAIS', 'INTERDISCIPLINAR EM CIÊNCIAS NATURAIS E MATEMÁTICA', 'INTERDISCIPLINAR EM CULTURA, LINGUAGENS E TECNOLOGIAS APLICADAS', 'INTERDISCIPLINAR EM EDUCAÇÃO NO CAMPO', 'INTERDISCIPLINAR EM ENERGIA E SUSTENTABILIDADE', 'INTERDISCIPLINAR EM ESTUDOS AFRICANOS E AFRO-BRASILEIROS', 'INTERDISCIPLINAR EM HUMANIDADES', 'INTERDISCIPLINAR EM MOBILIDADE', 'INTERDISCIPLINAR EM SAÚDE', 'IRRIGAÇÃO E DRENAGEM', 'JOGOS DIGITAIS', 'JORNALISMO', 'JORNALISMO EM MULTIMEIOS', 'LATICÍNIOS', 'LAZER E TURISMO', 'LETRAS', 'LETRAS - ALEMÃO', 'LETRAS - ARTES E MEDIAÇÃO CULTURAL', 'LETRAS - ESPANHOL', 'LETRAS - ESPANHOL E LITERATURA HISPÂNICA', 'LETRAS - ESPANHOL E PORTUGUÊS COMO LÍNGUAS ESTRANGEIRAS', 'LETRAS - ESTUDOS LITERÁRIOS', 'LETRAS - FRANCÊS', 'LETRAS - GREGO', 'LETRAS - INGLÊS', 'LETRAS - ITALIANO', 'LETRAS - JAPONÊS', 'LETRAS - LATIM', 'LETRAS - LETRAS CLÁSSICAS (GREGO E LATIM)', 'LETRAS - LIBRAS', 'LETRAS - LIBRAS/LÍNGUA ESTRANGEIRA', 'LETRAS - LÍNGUA E LITERATURA ESPANHOLA', 'LETRAS - LÍNGUA E LITERATURA FRANCESA', 'LETRAS - LÍNGUA E LITERATURA INGLESA', 'LETRAS - LÍNGUA E LITERATURA JAPONESA', 'LETRAS - LÍNGUA E LITERATURA PORTUGUESA', 'LETRAS - LÍNGUA E LITERATURAS DE LÍNGUA INGLESA', 'LETRAS - LINGUA ESPANHOLA', 'LETRAS - LÍNGUA ESPANHOLA E LITERATURA', 'LETRAS - LÍNGUA FRANCESA E LITERATURA', 'LETRAS - LÍNGUA HISPANO - AMERICANA', 'LETRAS - LÍNGUA INGLESA', 'LETRAS - LÍNGUA INGLESA E RESPECTIVAS LITERATURAS', 'LETRAS - LÍNGUA PORTUGUESA', 'LETRAS - LÍNGUA PORTUGUESA COM DOMÍNIO DE LIBRAS', 'LETRAS - LÍNGUA PORTUGUESA E LITERATURAS DE LÍNGUA PORTUGUESA', 'LETRAS - LÍNGUAS ADICIONAIS INGLÊS, ESPANHOL E RESPECTIVAS LITERATURAS', 'LETRAS - LINGUÍSTICA', 'LETRAS - POLONÊS', 'LETRAS - PORTUGUÊS', 'LETRAS - PORTUGUÊS DO BRASIL COMO SEGUNDA LÍNGUA', 'LETRAS - PORTUGUÊS E ALEMÃO', 'LETRAS - PORTUGUÊS E ESPANHOL', 'LETRAS - PORTUGUÊS E FRANCÊS', 'LETRAS - PORTUGUÊS E INGLÊS', 'LETRAS - PORTUGUÊS E ITALIANO', 'LETRAS - PORTUGUÊS E LITERATURA', 'LETRAS - PORTUGUÊS E LITERATURAS', 'LETRAS - PORTUGUÊS E LITERATURAS DA LÍNGUA PORTUGUESA', 'LETRAS - PORTUGUÊS E LITERATURAS DE LÍNGUA PORTUGUESA', 'LETRAS - PORTUGUÊS, E/OU ALEMÃO, E/OU GREGO, E/OU LATIM', 'LETRAS - REDAÇÃO E REVISÃO DE TEXTOS', 'LETRAS - TRADUÇÃO ESPANHOL', 'LETRAS - TRADUÇÃO ESPANHOL - PORTUGUÊS', 'LETRAS - TRADUÇÃO FRANCÊS', 'LETRAS - TRADUÇÃO INGLÊS', 'LETRAS - TRADUÇÃO INGLÊS - PORTUGUÊS', 'LETRAS COM PORTUGUÊS E ESPANHOL', 'LETRAS LÍNGUA ESTRANGEIRA APLICADA', 'LETRAS MODERNAS - PORTUGUÊS/INGLÊS E RESPECTIVAS LITERATURAS', 'LETRAS PORTUGUÊS E ESPANHOL E RESPECTIVAS LITERATURAS', 'LETRAS PORTUGUÊS E FRANCÊS', 'LETRAS PORTUGUÊS E INGLÊS', 'LETRAS VERNÁCULAS', 'LETRAS VERNÁCULAS - PORTUGUÊS E RESPECTIVAS LITERATURAS', 'LICENCIATURA INTEGRADA EM CIÊNCIAS, MATEMÁTICA E LINGUAGENS', 'LÍNGUA E LITERATURAS DA LÍNGUA INGLESA', 'LÍNGUA PORTUGUESA E RESPECTIVAS LITERATURAS', 'LINGUAGEM E COMUNICAÇÃO', 'LINGUAGENS E CÓDIGOS - LÍNGUA PORTUGUESA', 'LINGUAGENS E CÓDIGOS - MÚSICA', 'LÍNGUAS ESTRANGEIRAS APLICADAS ÀS NEGOCIAÇÕES INTERNACIONAIS', 'LINGUÍSTICA', 'LOGÍSTICA', 'LUTERIA', 'MANUTENÇÃO DE AERONAVES', 'MANUTENÇÃO INDUSTRIAL', 'MARKETING', 'MATEMÁTICA', 'MATEMÁTICA - LICENCIATURA OU BACHARELADO', 'MATEMÁTICA APLICADA', 'MATEMÁTICA APLICADA A NEGÓCIOS', 'MATEMÁTICA APLICADA E COMPUTAÇÃO CIENTÍFICA', 'MATEMÁTICA APLICADA E COMPUTACIONAL', 'MATEMÁTICA COMPUTACIONAL', 'MATEMÁTICA E COMPUTAÇÃO CIENTÍFICA', 'MATEMÁTICA INDUSTRIAL', 'MECÂNICA INDUSTRIAL', 'MECATRÔNICA INDUSTRIAL', 'MEDICINA', 'MEDICINA VETERINÁRIA', 'METEOROLOGIA', 'MINERAÇÃO', 'MODA', 'MODA E DESIGN', 'MODA, DESIGN E ESTILISMO', 'MUSEOLOGIA', 'MÚSICA', 'MÚSICA - CANTO', 'MÚSICA - CIÊNCIAS MUSICAIS', 'MÚSICA - COMPOSIÇÃO', 'MÚSICA - FLAUTA TRANSVERSAL', 'MÚSICA - PIANO', 'MÚSICA - VIOLÃO', 'MÚSICA - VIOLINO', 'MÚSICA POPULAR', 'MUSICOTERAPIA', 'NANOTECNOLOGIA', 'NEGÓCIOS IMOBILIÁRIOS', 'NUTRIÇÃO', 'NUTRIÇÃO E METABOLISMO', 'OBSTETRÍCIA', 'OCEANOGRAFIA', 'OCEANOLOGIA', 'ODONTOLOGIA', 'OFTÁLMICA', 'PEDAGOGIA', 'PEDAGOGIA - EDUCAÇÃO DO CAMPO', 'PEDAGOGIA - EDUCAÇÃO INFANTIL E ANOS INICIAIS DO ENSINO FUNDAMENTAL', 'PEDAGOGIA BILINGUE  - LIBRAS/PORTUGUÊS', 'PINTURA', 'POLÍTICAS PÚBLICAS', 'PROCESSOS AMBIENTAIS', 'PROCESSOS ESCOLARES', 'PROCESSOS GERENCIAIS', 'PROCESSOS METALÚRGICOS', 'PROCESSOS QUÍMICOS', 'PRODUÇÃO CÊNICA', 'PRODUÇÃO CULTURAL', 'PRODUÇÃO DE CACHAÇA', 'PRODUÇÃO DE GRÃOS', 'PRODUÇÃO E POLÍTICA CULTURAL', 'PRODUÇÃO MULTIMÍDIA', 'PRODUÇÃO PUBLICITÁRIA', 'PRODUÇÃO SUCROALCOOLEIRA', 'PSICOLOGIA', 'PSICOLOGIA - FORMAÇÃO DE PSICÓLOGO', 'PSICOPEDAGOGIA', 'PUBLICIDADE E PROPAGANDA', 'QUÍMICA', 'QUÍMICA - LICENCIATURA OU BACHARELADO', 'QUÍMICA - QUÍMICA FORENSE', 'QUÍMICA AMBIENTAL', 'QUÍMICA DE ALIMENTOS', 'QUÍMICA DO PETRÓLEO', 'QUÍMICA INDUSTRIAL', 'QUÍMICA MEDICINAL', 'QUÍMICA TECNOLÓGICA', 'QUÍMICA TECNOLÓGICA E INDUSTRIAL', 'RADIALISMO', 'RÁDIO, TV E INTERNET', 'RADIOLOGIA', 'REDES DE COMPUTADORES', 'RELAÇÕES ECONÔMICAS INTERNACIONAIS', 'RELAÇÕES INTERNACIONAIS', 'RELAÇÕES INTERNACIONAIS E INTEGRAÇÃO', 'RELAÇÕES PÚBLICAS', 'SANEAMENTO AMBIENTAL', 'SAÚDE COLETIVA', 'SAÚDE PÚBLICA', 'SECRETARIADO', 'SECRETARIADO EXECUTIVO', 'SECRETARIADO EXECUTIVO BILÍNGUE', 'SEGURANÇA NO TRABALHO', 'SEGURANÇA PÚBLICA', 'SERVIÇO SOCIAL', 'SISTEMA DE INFORMAÇÃO', 'SISTEMAS DE ENERGIA', 'SISTEMAS DE INFORMAÇÃO', 'SISTEMAS DE TELECOMUNICAÇÕES', 'SISTEMAS E MÍDIAS DIGITAIS', 'SISTEMAS ELÉTRICOS', 'SISTEMAS PARA INTERNET', 'SOCIOLOGIA', 'TEATRO', 'TEATRO - LICENCIATURA OU BACHARELADO', 'TECNOLOGIA DA INFORMAÇÃO', 'TECNOLOGIAS DA INFORMAÇÃO E COMUNICAÇÃO', 'TELEMÁTICA', 'TEORIA DA DANÇA', 'TEORIA, CRÍTICA E HISTÓRIA DA ARTE', 'TERAPIA OCUPACIONAL', 'TÊXTIL E MODA', 'TOXICOLOGIA AMBIENTAL', 'TOXICOLOGIA ANALÍTICA', 'TRADUÇÃO', 'TRADUÇÃO E INTERPRETAÇÃO EM LIBRAS/PORTUGUÊS', 'TRADUÇÃO E INTERPRETAÇÃO EM LÍNGUA BRASILEIRA DE SINAIS - LIBRAS/LÍNGUA PORTUGUESA', 'TRANSPORTE TERRESTRE', 'TURISMO', 'TURISMO BINACIONAL', 'TURISMO E HOTELARIA', 'TURISMO E MEIO AMBIENTE', 'TURISMO PATRIMONIAL E SOCIOAMBIENTAL', 'URBANISMO', 'VITICULTURA E ENOLOGIA', 'ZOOTECNIA']

question1 = Quiz::Question.create!(
  id: 54,
  quiz_form_id: form2.id,
  statement: 'Qual o curso que você deseja?',
  question_type:  'select'
)

question2 = Quiz::Question.create!(
  id: 55,
  quiz_form_id: form2.id,
  statement: 'Você teria algum desses cursos como segunda opção?',
  question_type:  'select'
)

courses.each_with_index do |description, index|
  Quiz::Alternative.create!(
    quiz_question_id: question1.id,
    description: description,
    value: index)

  Quiz::Alternative.create!(
    quiz_question_id: question2.id,
    description: description,
    value: index)
end

question3 = Quiz::Question.create!(
  id: 56,
  quiz_form_id: form2.id,
  statement: 'Qual o seu estado?',
  question_type:  'select'
)

['Acre - AC', 'Alagoas - AL', 'Amapá - AP', 'Amazonas - AM', 'Bahia - BA', 'Ceará - CE', 'Distrito Federal - DF', 'Espírito Santo - ES', 'Goiás - GO', 'Maranhão - MA', 'Mato Grosso - MT', 'Mato Grosso do Sul - MS', 'Minas Gerais - MG', 'Pará - PA', 'Paraíba - PB', 'Paraná - PR', 'Pernambuco - PE', 'Piauí - PI', 'Rio de Janeiro - RJ', 'Rio Grande do Norte - RN', 'Rio Grande do Sul - RS', 'Rondônia - RO', 'Roraima - RR', 'Santa Catarina - SC', 'São Paulo - SP', 'Sergipe - SE', 'Tocantins - TO'].each_with_index do |description, index|
  Quiz::Alternative.create!(
    quiz_question_id: question3.id,
    description: description,
    value: index
  )
end

question4 = Quiz::Question.create!(
  id: 57,
  quiz_form_id: form2.id,
  statement: 'Qual tipo de escola você estudou no Ensino Médio?',
  question_type:  'select'
)

["Pública",
"Privada",
"Militar",
"Instituto Federal"].each_with_index do |description, index|
  Quiz::Alternative.create!(
    quiz_question_id: question4.id,
    description: description,
    value: index
  )
end

question5 = Quiz::Question.create!(
  id: 58,
  quiz_form_id: form2.id,
  statement: 'No próximo ano você? ',
  question_type:  'select'
)

["Ainda estarei no colégio",
"Já estarei formado no colégio"].each_with_index do |description, index|
  Quiz::Alternative.create!(
    quiz_question_id: question5.id,
    description: description,
    value: index
  )
end

question6 = Quiz::Question.create!(
  id: 59,
  quiz_form_id: form2.id,
  statement: 'Você ainda tem algum vestibular regional para fazer?',
  question_type:  'select'
)

["Sim",
"Não"].each_with_index do |description, index|
  Quiz::Alternative.create!(
    quiz_question_id: question6.id,
    description: description,
    value: index
  )
end

Quiz::Question.create!(
  id: 60,
  quiz_form_id: form2.id,
  statement: 'Como você está se sentindo depois da prova? ',
  question_type:  'text'
)
