name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: backend-api_test
          postgresql user: postgres
          postgresql password: postgres
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.51.3
        with:
          ruby-version: 2.6.6
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install moment --save
          npm install dredd --save
      - name: Set up environment variables
        run: |
          cp .env.sample .env
          cp config/database.yml.sample config/database.yml
      - name: Run integration tests
        run: sh bin/integration
      - name: Integration coverage report
        if: ${{ always() }}
        run: bash bin/integration_coverage
