# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Unity Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: backend-api_test
          postgresql user: postgres
          postgresql password: postgres
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.51.3
        with:
          ruby-version: 2.6.6
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Set up environment variables
        run: |
          cp .env.sample .env
          cp config/database.yml.sample config/database.yml
      - name: Create test database
        run: RAILS_ENV=test bundle exec rake db:create
      - name: Migrate test database
        run: RAILS_ENV=test bundle exec rake db:migrate
      - name: Run tests
        run: bundle exec rspec
      - name: Run Code Climate
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: b8351ecbbdec65b3967fed954e5619466820a8baf2a0a7272620eb80b8d88449
